# Events and methods binding dictionary

binding_dict = {
    'play' :                    "play" ,
    'stop' :                    "stop" ,
    'pause' :                   "pause" ,
    'LoadFIle' :                "load_file" ,
    'selectFile' :              "select_file" ,
    'key' :                     "key_press" ,
    'DoubleClick' :             "double_click",
    'finderKeyPressed' :        "finder",
    'selectDir' :               "load_dir",
    'volumeChanged' :           "volume_changed",
    'Resume' :                  "resume",
    'Radios':                   "btRadioMusic_click",
    'selectedDir' :             "add_songs",
    'addRadio':                 "add_radio",
    'Musica':                   "btRadioMusic_click",
    'addUri':                   "add_uri",
    'cancelUri':                "cancel_uri",
    'seek' :                    "seek",
    'menu_randomizer' :         "randomizer",
    'cancelRandomList' :        "cancel_random_list",
    'aceptRandomList' :         "accept_random_list",
    'randomList' :              "random_play",
    'scoreAccept' :             "score_accept",
    'scoreCancel' :             "score_cancel",
    'RankingShow' :             "ranking_show",

    # methods of close signals
    "delete_event":               "select_file",
    "destroy":                    "select_file",
    "delete_event":               "update_songs",
    "destroy":                    "update_songs",
    "delete_event":               "cancel_uri",
    "destroy":                    "cancel_uri",
    "delete_event":               "cancel_random_list",
    "destroy":                    "cancel_random_list",
    "delete_event":               "score_cancel",
    "destroy":                    "score_cancel",
    "delete_event":               "hide_ranking",
    "destroy":                    "hide_ranking",
}
